name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: appgimnasia.login

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Obtener short commit
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Login en GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build imagen Docker con tags
      run: |
        IMAGE=ghcr.io/${{ github.repository_owner }}/appgimnasia.login
        IMAGE_LOWER=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')
        docker build -t $IMAGE_LOWER:latest -t $IMAGE_LOWER:sha-${{ env.SHORT_SHA }} .
        
    - name: Push de imágenes
      run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/appgimnasia.login
          IMAGE_LOWER=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')
          docker push $IMAGE_LOWER:latest
          docker push $IMAGE_LOWER:sha-${{ env.SHORT_SHA }}

